version: '3.8'
services:
  mongodb:
    image: mongo:4.4.0-rc7-bionic
    container_name: db_confesionario_cont
    command: --serviceExecutor adaptive
    volumes:
      - ./mongodb_data_container:/data/db
    ports:
        - "27017:27017"
    expose:
      - "27017"
  app:
    build: .
    image: app_confesionario_im
    container_name: app_confesionario_cont
    restart: always
    depends_on:
        - mongodb
    volumes:
        - .:/app
        - /app/node_modules
    ports:
        - "3000:3000"
    command: ./wait-for-it.sh mongodb:27017 -- pm2-runtime src/index.js
